"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import os

import raven

from .base import *  # noqa

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV.str("SECRET_KEY", "Keep it secret!")

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = ENV.bool("DEBUG", True)
ENABLE_DEBUG_TOOLBAR = DEBUG and ENV.bool("ENABLE_DEBUG_TOOLBAR", False)

ALLOWED_HOSTS = ENV.list("ALLOWED_HOSTS", [])
INTERNAL_IPS = ENV.list("INTERNAL_IPS", default=("127.0.0.1", ))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

EXTERNAL_APPS = [
    "django_celery_results",
]

PROJECT_APPS = [
    "core.email",
]

INSTALLED_APPS.extend(EXTERNAL_APPS + PROJECT_APPS)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Django Debug Toolbar settings
# https://django-debug-toolbar.readthedocs.io/en/stable/configuration.html

if ENABLE_DEBUG_TOOLBAR:
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")

    DEBUG_TOOLBAR_CONFIG = {
        "RESULTS_CACHE_SIZE": 50,
        "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG,
    }

    DEBUG_TOOLBAR_PANELS = [
        "debug_toolbar.panels.timer.TimerPanel",
        "debug_toolbar.panels.sql.SQLPanel",
    ]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    "default": ENV.db_url("DATABASE_URL", default="sqlite://:memory:"),
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "collectstatic")

# Redis settings
REDIS_URL = "redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_PATH}".format(
    REDIS_HOST=ENV.str("REDIS_HOST", "127.0.0.1"),
    REDIS_PORT="6379",
    REDIS_PATH="0",
)

# Celery settings
# http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["pickle", "json", "msgpack", "yaml"]
CELERY_TASK_ALWAYS_EAGER = ENV.bool("CELERY_TASK_ALWAYS_EAGER", False)

CELERY_ROUTES = {
    "accounts.tasks.AsyncEmailTask": {"queue": "accounts"},
}

# Raven settings
RAVEN_DSN = ENV.str("RAVEN_DSN", None)
if RAVEN_DSN:
    INSTALLED_APPS.append("raven.contrib.django.raven_compat")
    RAVEN_CONFIG = {
        "dsn": RAVEN_DSN,
        "release": raven.fetch_git_sha(os.path.dirname(os.pardir)),
    }


# Email settings

DEFAULT_FROM_EMAIL = "from@example.com"
EMAIL_BASE_TEMPLATE = "email/base.html"
EMAIL_HOST = ENV.str("EMAIL_HOST", "localhost")
EMAIL_PORT = ENV.int("EMAIL_PORT", 25)
EMAIL_BACKEND_CONFIG = ENV.str("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
