version: "2"

services:
  project_img:
    build: .
    image: dj-project:latest

  project_app:
    image: dj-project:latest
    volumes:
      - .:/project

  db:
    image: postgres:10
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    volumes:
      - redis:/data

  celery:
    extends: project_app
    depends_on:
      - db
      - redis
    command: ./wait-for-it.sh db:5432 -- celery -A project worker -l info
    environment:
      C_FORCE_ROOT: "1"

  project:
    extends: project_app
    depends_on:
      - db
      - redis
      - celery
    command: ./wait-for-it.sh db:5432 -- python manage.py runserver 0:8000
    ports:
      - "8000:8000"

volumes:
  db:
  redis: