---

- name: Install reuired system packages
  become: true
  apt:
    name: [
      "build-essential", "python3", "python3-dev",
      "libpq-dev", "python3-pip", "python3-setuptools",
      "python3-venv", "python-psycopg2"
    ]
  tags:
    - python

- name: Install Setuptools for python2 # https://github.com/ansible/ansible/issues/47361
  become: true
  apt:
    name: "python-setuptools"
  tags:
    - python

- name: Install PIP packages
  become: true
  pip:
    executable: pip3
    name: ["pip", "setuptools", "pipenv"]
    extra_args: --upgrade
  tags:
    - python